export const Speakers = [
  {
    photo: "/images/politicians/kiriakos_mitsotakis.jpg",
    name: "Κυριάκος Μητσοτάκης",
    party: "ΝΕΑ ΔΗΜΟΚΡΑΤΙΑ",
    description: "Έλληνας πολιτικός, πρωθυπουργός της Ελλάδας",
    age: 56,
    gender: "male",
  },
  {
    photo: "/images/politicians/stefanos_kaselakis.jpg",
    name: "Στέφανος Κασελάκης",
    party: "ΣΥΡΙΖΑ",
    description: "Έλληνας επιχειρηματίας και πολιτικός",
    age: 36,
    gender: "male",
  },
  {
    photo: "/images/politicians/nikos_androulakis.jpg",
    name: "Νίκος Ανδρουλάκης",
    party: "ΠΑΣΟΚ",
    description: "Έλληνας πολιτικός, πρόεδρος του ΠΑΣΟΚ-Κίνημα Αλλαγής",
    gender: "male",
    age: 45,
  },
  {
    photo: "/images/politicians/alexis_tsipras.jpg",
    name: "Αλέξης Τσίπρας",
    party: "ΣΥΡΙΖΑ",
    description: "Έλληνας πολιτικός, πρώην πρωθυπουργός της Ελλάδας (2015-2019)",
    age: 50,
    gender: "male",
  },
  {
    photo: "/images/politicians/koutsoumpas.jpg",
    name: "Δημήτρης Κουτσούμπας",
    party: "ΚΚΕ",
    description: "Έλληνας πολιτικός και Γενικός Γραμματέας της Κ.Ε. του ΚΚΕ",
    age: 69,
    gender: "male",
  },
  {
    photo: "/images/politicians/konstantinos_tasoulas.jpg",
    name: "Κωνσταντίνος Τασούλας",
    party: "ΝΕΑ ΔΗΜΟΚΡΑΤΙΑ",
    description: "Πρόεδρος της Βουλής των Ελλήνων",
    age: 65,
    gender: "male",
  },
  {
    photo: "/images/politicians/nantia_giannakopoulou.jpg",
    name: "Νάντια Γιαννακοπούλου",
    party: "ΠΑΣΟΚ",
    description: "Ελληνίδα δικηγόρος και πολιτικός",
    age: 46,
    gender: "female",
  },
  {
    photo: "/images/politicians/adonis_georgiadis.jpg",
    name: "Άδωνις Γεωργιάδης",
    party: "ΝΕΑ ΔΗΜΟΚΡΑΤΙΑ",
    description: "Υπουργός Υγείας της Ελληνικής Δημοκρατίας, Αντιπρόεδρος της ΝΔ",
    age: 52,
    gender: "male",
  },
];
